spring:
  datasource:
    url: jdbc:mysql://localhost/test?serverTimezone=UTC
    username: root
    password: dolape8755
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false
