spring:
  datasource:
    url: jdbc:mysql://localhost/Grupo-14-bdd-OO2-2020?serverTimezone=UTC
    username: root
    password: root
    #initialization-mode: always #never
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false
